# File: verify_solution.py
import sys

class SolutionVerifier:
    def __init__(self, mapping_file="variable_map.txt"):
        self.unstable_exceptions = {5, 8, 9, 107, 109, 147, 203, 205}
        self.var_map = self.load_mapping(mapping_file)

    def load_mapping(self, filepath):
        """Loads variable index mapping generated by cnf_generator.py"""
        v_map = {}
        try:
            with open(filepath, "r") as f:
                for line in f:
                    if line.strip():
                        label, idx = line.strip().split(":")
                        v_map[int(idx)] = label
        except FileNotFoundError:
            print(f"[ERROR] Mapping file {filepath} missing. Run generator first.")
        return v_map

    def verify_sat_output(self, sat_output_path):
        """Validates the true assignments against physical constraints."""
        if not self.var_map:
            return False

        true_literals = set()
        try:
            with open(sat_output_path, "r") as f:
                content = f.read().split()
                # Assuming standard SAT format: array of literals ending with 0
                for token in content:
                    val = int(token)
                    if val > 0:
                        true_literals.add(val)
        except Exception as e:
            print(f"[ERROR] Failed to read SAT output: {e}")
            return False

        # Physical Rule Validation
        is_valid = True
        active_masses = {}

        for lit in true_literals:
            if lit in self.var_map:
                label = self.var_map[lit]
                
                # Check for active mass state
                if "_M" in label:
                    parts = label.split("_M")
                    particle = parts[0]
                    mass = int(parts[1])
                    
                    if particle in active_masses:
                        print(f"[VIOLATION] Double mass state detected for {particle}: {active_masses[particle]} AND {mass}")
                        is_valid = False
                    active_masses[particle] = mass
                    
                    if mass in self.unstable_exceptions:
                        print(f"[VIOLATION] Solver allowed unstable exception mass {mass} on {particle} without breaking.")
                        is_valid = False

        if is_valid:
            print("[SUCCESS] 3SAT solution perfectly mirrors all spreadsheet validation rules.")
        return is_valid

if __name__ == "__main__":
    # Example execution hook
    verifier = SolutionVerifier()
    # verifier.verify_sat_output("solver_result.txt")
